apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
  - frontend.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: frontend.default.svc.cluster.local
        port:
          number: 3000
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: frontend
spec:
  host: frontend.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: backend
spec:
  hosts:
  - backend.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: backend.default.svc.cluster.local
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: backend
spec:
  host: backend.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: minio
spec:
  hosts:
  - minio-s3.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: minio-s3.default.svc.cluster.local
        port:
          number: 9000
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: minio
spec:
  host: minio-s3.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
