apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  # name: letsencrypt-prod-cloudflare
  name: letsencrypt-staging-cloudflare
spec:
  acme:
    # server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: joaojunior.b22@gmail.com
    privateKeySecretRef:
      # name: letsencrypt-prod-account-key
      name: letsencrypt-staging-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token