kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31000
    hostPort: 80
  - containerPort: 31001
    hostPort: 443
- role: control-plane
- role: worker
- role: worker