apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kind-cluster-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.200-192.168.0.255
  - 177.93.252.103/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - kind-cluster-pool
  interfaces:
  - wlan0
